server:
  port: 8081
 
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/som
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
 
springdoc:
  swagger-ui:
    path: /swagger-ui.html
 
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans
 
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
 
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
 
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s
      paymentService:
        maxAttempts: 3
        waitDuration: 2s
