
server:
  port: 8082
 
spring:
  application:
    name: payment-service
 
  datasource:
    url: jdbc:postgresql://localhost:5432/som
    username: postgres
    password: 123456789
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
